# Generated by Django 2.2.1 on 2019-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=3000)),
                ('birth', models.DateTimeField()),
                ('nationality', models.CharField(choices=[('KR', 'Korea'), ('JP', 'Japan'), ('TW', 'Tiwan')], max_length=30)),
                ('position', models.CharField(max_length=30)),
            ],
        ),
    ]
